openedx/super-csv

- manage.py
- super_csv/__init__.py
- super_csv/admin.py
- super_csv/csv_processor.py
- super_csv/models.py
- super_csv/tasks.py
- tests/test_csv.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> Catch an exception for validation errors, instead of using a response bool

- super_csv/__init__.py
- super_csv/admin.py
- super_csv/csv_processor.py
- super_csv/models.py
- super_csv/tasks.py
- tests/test_csv.py
Changed the error handling to store a copy of the original data with an additional "error" column.
> Changed error handling

- super_csv/csv_processor.py
Exported rows were showing up with `blah,None,None`. etc
> Don't encode None as 'None'

- super_csv/__init__.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> Bump version

- CHANGELOG.rst
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
- setup.py
- super_csv/__init__.py
- super_csv/csv_processor.py
- super_csv/mixins.py
- super_csv/models.py
- super_csv/serializers.py
**Description:** adds an endpoint for bulk grade management operation history
**JIRA:** https://openedx.atlassian.net/browse/EDUCATOR-4367
**Dependent of:** https://github.com/edx/edx-bulk-grades/pull/5 & https://github.com/edx/gradebook/pull/98 
**Reviewers:**
finished.
> add serializing of relevant portions of history

- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
- super_csv/__init__.py
**Description:** addresses https://github.com/edx/super-csv/pull/6#discussion_r300896116
**Reviewers:**
finished.
> Remove incorrect django rest framework invocation

- super_csv/__init__.py
- super_csv/mixins.py
- tests/test_csv.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> Quote the checksum, to prevent spreadsheet transformation

- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- requirements/travis.txt
- super_csv/__init__.py
- super_csv/apps.py
- super_csv/common_settings.py
- super_csv/models.py
- super_csv/signals.py
- super_csv/tasks.py
- test_settings.py
- tests/test_models.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> Expire uploaded data after 90 days

- README.rst
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> EDUCATOR-4626

- openedx.yaml
**Description:** openedx.yaml is missing items needed to support this repo
**JIRA:** [EDUCATOR-4739](https://openedx.atlassian.net/browse/EDUCATOR-4739)
**Reviewers:**
finished.
> Update owner; add supporting team

- .travis.yml
- CHANGELOG.rst
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
- setup.py
- super_csv/__init__.py
- super_csv/apps.py
- super_csv/csv_processor.py
- super_csv/mixins.py
- super_csv/models.py
- tox.ini
Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1572).
> Updated the tox and travis configs -- BOM-1572

- pylintrc
- pylintrc_tweaks
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/quality.in
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
- super_csv/csv_processor.py
- super_csv/models.py
- tox.ini
**Issue:** [BOM-1663](https://openedx.atlassian.net/browse/BOM-1663)
- Removed `caniusepython3` package.
- Removed `python_2_unicode_compatible` package.
> Removing caniusepython3 && python_2_unicode_compatible

- CHANGELOG.rst
- super_csv/__init__.py
**Issue:** [BOM-1663](https://openedx.atlassian.net/browse/BOM-1663)
- Releasing new version `0.9.9`
> Releasing new version 0.9.9

- docs/conf.py
- super_csv/csv_processor.py
- super_csv/mixins.py
- super_csv/models.py
**Issue:** [BOM-1819](https://openedx.atlassian.net/browse/BOM-1819)
- Remove usages of package `six`.
> Remove usages of package six

- CHANGELOG.rst
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
- super_csv/__init__.py
- super_csv/mixins.py
- super_csv/tasks.py
**Description:**
Add code_owner custom attribute to celery tasks for monitoring purposes.
**JIRA:**
ARCHBOM-1636
Will test via edx-platform PR.
finished.
> ARCHBOM-1636: add code_owner to celery tasks

- .github/workflows/upgrade-python-requirements.yml
**Description:** change requirements upgrade email to new aurora support
**JIRA:** [AU-778](https://2u-internal.atlassian.net/browse/AU-778)
> build: change requirements upgrade email

- .github/workflows/ci.yml
- requirements/ci.in
- requirements/ci.txt
- requirements/dev.txt
Context: https://about.codecov.io/blog/message-regarding-the-pypi-package/
> build: remove unnecessary codecov package & upgrade GHA

- super_csv/__init__.py
- tox.ini
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> fix: env42 added

- LICENSE.txt
**Description:** Just updating the license file to the correct one
> docs: Update LICENSE to the actual Apache 2 license

- openedx.yaml
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> chore: update repo ownership

- catalog-info.yaml
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> doc: Add catalog-info.yaml
